### ISSUE TITLE
update source fields

### ISSUE THREAD

**Issue by vadekh** [digitallinguistics/spec#337]
This is a meta-issue for planning changes to source/bibliography fields, and tracking those issues.

# Places to Address
* `Lexeme` (remove field from Lexeme?)
* `LexemeForm`
* `Note` (#300)
* `Sense` (source/speaker)
* `Utterance` (source/speaker) (#320)

# Additional Changes
- [x] update any relevant example data
  - **NB:** This needs to be done for any schemas that also _contain_ one of the affected schemas in the example data.
- [x] update version numbers of affected schemas
  - **NB:** The type of version bump to make depends on the difference between this PR and the current `master` branch, _not_ the difference between this PR and earlier versions of this PR.

# Original Proposals
- [x] `Note.source` should always be a `Person` object (ie who wrote the Note, even if the object is just their name)
- [x] Remove required properties for `Person` objects (unless there is a functional reason to require family and given names)
- [x] `Utterance.speaker` should be a `Person` object
- [x] update description of `Utterance.speaker` - it no longer needs to be an abbreviation
- [x] Add `Utterance.source` for Utterances taken out of context, like sets of utterances to be used as examples in publications. There's not going to be any sort of database to cross-reference. The user just needs to be able to identify where the data comes from. Strongly recommended when an `Utterance` is not part of a Text - `MultiLangString`
- [x] The sources property in various schemas should be an array of DatabaseReferences to either Person objects or BibliographicReference objects. This affects the following properties:
- [x] Lexeme.sources
- [x] LexemeForm.sources
- [x] Sense.sources
The sources fields should not contain DatabaseReferences to Texts, Utterances, Word Tokens, or Morpheme Tokens.

**Comment by vadekh** [comment]
Lexeme, LexemeForm, and Sense all already have a bibliographicReference array field. Should this be combined into the Sources array? Or should that remain separate and the Sources field require a Person reference. @dwhieb

**Comment by vadekh** [comment]
never mind. I see the separate functionality of the Bibliographic References arrays.

**Comment by dwhieb** [comment]
@Calvin1119 had [this comment](https://github.com/digitallinguistics/spec/pull/322#issuecomment-543418453) about the sources fields (recopied here):

> It does seem a little confusing that there are some source(s) fields that allow both Person and BibliographicReference objects and some that only take Person objects. Also, for those types of source fields (as seen in Sense), there doesn't seem to be any actual validation that these objects are actually of the correct types (Person/BibliographicRef instead of any other type of DatabaseRef). This PR should be good to go, but that might be another issue to take a look at in the future.

I think he's right about the inconsistencies, and we should come up with a clear and consistent plan for handling the relevant properties that are affected by this issue before we commit @vadekh's changes to the master branch. This means that @vadekh will likely have to update the code for PR #322 again once these decisions are made.

**Comment by vadekh** [comment]
@dwhieb @Calvin1119 I agree! I was unsure how, if at all, I would be able to validate a field against more than one schema, in an either or manner. Is there a way to do that since the objects are technically of the DatabaseReference type? If so, it might be worth reviewing other properties that use DatabaseReference throughout spec, although that isn't an urgent issue.

**Comment by dwhieb** [comment]
The motivation behind all these `Source(s) / References` fields is that it's best practice to document the source of each fact about a language. So if there's a word listed in the dictionary, we need to know which speakers used that word. If there's a sense listed for a word, we need to know which speakers used the word with that sense.

Sometimes we _don't_ know the exact speaker who was the source of the information, but we know a book / document / manuscript / etc. where the information came from. In these cases, we need to know the bibliographic information about that source.

Previously I suggested using the `Source(s)` fields to cover both of these use cases, allowing a source to be either a bibliographic reference, or a reference to a person. @Calvin1119's and @vadekh's comments above convinced me this is a mistake.

My proposal now is that each of the relevant objects has two fields:
- `Sources`: an array of database references / pointers to people
- `References`: an array of database references / pointers to bibliography items

**Other Thoughts**
- It might be clearer if we used the term `bibliography` instead of `references` for the array of bibliographic references.
- Both the `Source(s)` and `References/Bibliography` arrays should contain pointers to other objects in the database (in other words, they should contain `DatabaseReference` objects).
- We might need to make a distinction between a _Bibliographic Source_ and a _Bibliographic Reference/Citation_. A Bibliographic Source would contain all the metadata about a particular item (author, title, year, etc.), whereas a Bibliographic Reference would be basically just a pointer to a Bibliographic Source, and the page number where the item can be found in that source.
- The `DatabaseReference` object has a `referenceType` field which indicates what the `DatabaseReference` object is meant to be pointing to. So, if you're using a `DatabaseReference` to point to a `Person`, the value of the `referenceType` field in the `DatabaseReference` would be `Person`.

@vadekh
@Calvin1119
@monicamacaulay

Thoughts?

**Comment by dwhieb** [comment]
@vadekh The JSON Schema spec allows you to specify that a given field or items in an array are valid if they match any of a set of specified schemas. So you can say that each item in an array must match either schema X or Y. Pretty handy, but if we separate out the `Source(s)` and `References/Bibliography` fields, we won't need to use this feature (for this issue at least).

**Comment by vadekh** [comment]
@dwhieb Those proposed changes make sense! I think `source` for Person object sources makes sense. I think we should use the word `Citation` in the fields describing a pointer to a part of an entire reference element, because I think the term `Reference` leaves some ambiguity as to whether the object is an entire bibliographic entry, or just a page.

**Comment by vadekh** [comment]
I've implemented some changes in the PR, separating the BibliographicReference sources from the Person sources. @dwhieb
