### ISSUE TITLE
Link issue on format.digitallinguistics.io home page

### ISSUE THREAD

**Issue by vadekh** [digitallinguistics/spec#394]
## Description

<img width="838" alt="Screen Shot 2020-08-03 at 2 46 53 PM" src="https://user-images.githubusercontent.com/36901345/89221101-5372d000-d598-11ea-8456-8ffcdfe016d1.png">
This link doesn't work on the website version of this document.

**Comment by vadekh** [comment]
It seems that the page just isnt up to date with the README displayed on the gitHub home, where the link is working. There, it has been changed to `[Developer Readme][Developer]`

**Comment by dwhieb** [comment]
The format.digitallinguistics.io website deploys from the `gh-pages` branch. That branch only gets updated when there's a release, which is intentional behavior. (It avoids the website displaying in-process changes or sets of changes.) It looks like this issue was already closed in c5a24bc1df29665dc8589278972253f4db245ccc, and is just waiting for the next release before it goes live. [Here's the blame report for that line of code.](https://github.com/digitallinguistics/spec/blame/master/.github/README.md#L202)

There are a few other things I wanted to commit to `master` before the v1.1.0 release:

https://github.com/digitallinguistics/spec/milestone/8
